### ISSUE TITLE
Order functions alphabetically

### ISSUE THREAD

**Issue by etiennebacher** [IndrajeetPatil/dotInternals#4]
Super useful package, I was clearly too lazy to rename all my internal functions :smile: 

I think the list of functions that were renamed should be ordered alphabetically, it would be easier to check that no mistakes were made.

**Comment by IndrajeetPatil** [comment]
Thanks, @etiennebacher!

Can you please check if this works as expected for you?

**Comment by etiennebacher** [comment]
Thanks, they are now correctly sorted
