### ISSUE TITLE
Mention that you have to rebuild the package before re-running dot_internals()

### ISSUE THREAD

**Issue by etiennebacher** [IndrajeetPatil/dotInternals#5]
After the first call to `dot_internals()`, there were some functions that were not prefixed with "." so I just re-ran `dot_internals()` to see if it would change anything. The problem is that running this function several times in a row adds several dots as prefix. It is only by looking at the source code that I saw a call to `library()` and understood that I had to re-build the package before re-running `dot_internals()`.

Maybe you could add a message saying that you have to re-build the package before running again `dot_internals()`?

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/IndrajeetPatil/dotInternals/commit/9c7d72364ac19b732af9fd9dede19178d778e91f

**Comment by IndrajeetPatil** [comment]
Thanks, @etiennebacher! It is important enough to be part of the message, indeed.
